;scm
;
; truck.scm -- simulating logical hidden markov models
;
;(ImplicationLink (stv 0.99 0.99)
;    (AndLink (stv 1 0)
;    (InheritanceLink (stv 1 0)
;        (VariableNode "R000")
;        (ConceptNode "symmetricRelation")
;    )
;    (PredicateNode "isDead")
;)

(AtTimeLink
  (TimeNode "6000:72000")
  (ConceptNode "Britney")
)
(VariableNode "LoadingSensor")
(VariableNode "GPS")
(ConceptNode "HMMState")
(ConceptNode "Moving")
(ConceptNode "Load")
(ConceptNode "Lost")
(ConceptNode "Delivery")
(InheritanceLink
  (ConceptNode "HMMState")
  (ConceptNode "Load")
)
(InheritanceLink
  (ConceptNode "HMMState")
  (ConceptNode "Moving")
)
(InheritanceLink
  (ConceptNode "HMMState")
  (ConceptNode "Lost")
)
(InheritanceLink
  (ConceptNode "HMMState")
  (ConceptNode "Delivery")
)
(ImplicationLink (stv 0.8 0.8)
  (TimeNode "20000")
      (SequentialAndLink (stv 1 0)
          (ConceptNode "Load")
          (ConceptNode "Moving")
  )
)
(AtTimeLink (stv 1 1)
  (TimeNode "10:20")
  (ConceptNode "Load")
)











(EvaluationLink (stv 0.8 0.4)
    (PredicateNode "friendOf")
    (ListLink (stv 1 0)
        (ConceptNode "Amir")
        (ConceptNode "Britney")
    )
)
(InheritanceLink (stv 0.999 0.999)
    (PredicateNode "friendOf")
    (ConceptNode "symmetricRelation")
)
(ConceptNode "transitiveRelation" (stv 1 0))
(InheritanceLink (stv 0.99 0.99)
    (PredicateNode "friendOf")
    (ConceptNode "transitiveRelation")
)
(PredicateNode "wasKilled" (stv 1 0))
(PredicateNode "isDead" (stv 1 0))
(ImplicationLink (stv 0.99 0.99)
    (PredicateNode "wasKilled")
    (PredicateNode "isDead")
)
(PredicateNode "pastForm" (stv 1 0))
(PredicateNode "kill" (stv 1 0))
(AndLink (stv 1 0.925926)
    (ImplicationLink (stv 1 0)
        (PredicateNode "killed")
        (ExecutionOutputLink (stv 0.99 0.99)
            (PredicateNode "pastForm")
            (PredicateNode "kill")
        )
    )
    (ImplicationLink (stv 1 0)
        (ExecutionOutputLink (stv 0.99 0.99)
            (PredicateNode "pastForm")
            (PredicateNode "kill")
        )
        (PredicateNode "killed")
    )
)
(EvaluationLink (stv 0.2 0.6)
    (PredicateNode "isDead")
    (ListLink (stv 1 0)
        (ConceptNode "Britney")
    )
)
(ConceptNode "x014" (stv 1 0))
(AndLink (stv 1 0)
    (EvaluationLink (stv 1 0)
        (PredicateNode "wasKilled")
        (ListLink (stv 1 0)
            (ConceptNode "x014")
        )
    )
    (EvaluationLink (stv 1 0)
        (PredicateNode "friendOf")
        (ListLink (stv 1 0)
            (ConceptNode "Amir")
            (ConceptNode "x014")
        )
    )
)
(ConceptNode "x012" (stv 0.05 0.99))
(EvaluationLink (stv 1 0)
    (PredicateNode "friendOf")
    (ListLink (stv 1 0)
        (ConceptNode "x012")
        (ConceptNode "Osama")
    )
)
(EvaluationLink (stv 1 0)
    (PredicateNode "wasKilled")
    (ListLink (stv 1 0)
        (ConceptNode "Muhammad")
    )
)
(EvaluationLink (stv 1 0)
    (PredicateNode "isDead")
    (ListLink (stv 1 0)
        (ConceptNode "Amir")
    )
)
(ConceptNode  "___PLN___" (stv 0 0))
(ConceptNode  "Osama" (stv 0.001 0.999))
(ConceptNode  "Abu" (stv 0.00001 0.999))
(ConceptNode  "Amir" (stv 0.00001 0.999))
(ConceptNode  "Britney" (stv 0.00001 0.999))
(ConceptNode  "Moses" (stv 0.00001 0.999))
(ConceptNode  "Judea" (stv 0.00001 0.999))
(ConceptNode  "Muhammad" (stv 0.00001 0.999))
(ConceptNode  "AlQaeda" (stv 0.0001 0.999))
(ConceptNode  "killer" (stv 0.05 0.999))
(ConceptNode  "terrorist"(stv 0.01 0.999))
(VariableNode "X007" (stv 1 0))
(VariableNode "X008" (stv 1 0))
(VariableNode "R000" (stv 1 0))
(ConceptNode "symmetricRelation" (stv 1 0))
(ForAllLink (stv 0.99 0.99)
    (ListLink (stv 1 0)
        (VariableNode "X007")
        (VariableNode "X008")
        (VariableNode "R000")
    )
    (ImplicationLink (stv 1 0)
        (AndLink (stv 1 0)
            (InheritanceLink (stv 1 0)
                (VariableNode "R000")
                (ConceptNode "symmetricRelation")
            )
            (EvaluationLink (stv 1 0)
                (VariableNode "R000")
                (ListLink (stv 1 0)
                    (VariableNode "X007")
                    (VariableNode "X008")
                )
            )
        )
        (EvaluationLink (stv 1 0)
            (VariableNode "R000")
            (ListLink (stv 1 0)
                (VariableNode "X008")
                (VariableNode "X007")
            )
        )
    )
)
(PredicateNode "test1" (stv 1 0))
(EvaluationLink (stv 1 0.999)
    (PredicateNode "test1")
    (ListLink (stv 1 0)
        (ConceptNode "Osama")
    )
)
(PredicateNode "test3" (stv 1 0))
(PredicateNode "test2" (stv 1 0))
(ImplicationLink (stv 1 0.999)
    (EvaluationLink (stv 1 0.25)
        (PredicateNode "test3")
        (ListLink (stv 1 0)
            (ConceptNode "Osama")
        )
    )
    (EvaluationLink (stv 1 0)
        (PredicateNode "test2")
        (ListLink (stv 1 0)
            (ConceptNode "Osama")
        )
    )
)
(InheritanceLink (stv 0.98 0.99)
    (ConceptNode "Osama")
    (ConceptNode "terrorist")
)
(PredicateNode "friendOf" (stv 1 0))
(ConceptNode "Britney2" (stv 1 0))
(ConceptNode "Osama2" (stv 1 0))
(EvaluationLink (stv 0.80 0.20)
    (PredicateNode "friendOf")
    (ListLink (stv 1 0)
        (ConceptNode "Britney2")
        (ConceptNode "Osama2")
    )
)
(PredicateNode "killed" (stv 1 0))
(PredicateNode "killerOf" (stv 1 0))
(InheritanceLink (stv 0.9 0)
    (EvaluationLink (stv 0.8 0)
        (PredicateNode "killerOf")
        (ListLink (stv 1 0)
            (ConceptNode "Osama")
            (ConceptNode "Moses")
        )
    )
    (EvaluationLink (stv 0.99 0.80)
        (PredicateNode "killed")
        (ListLink (stv 1 0)
            (ConceptNode "Moses")
            (ConceptNode "Osama")
        )
    )
)
(ConceptNode "R1" (stv 0.92 0))
(ConceptNode "X1" (stv 1 0))
(EvaluationLink (stv 0.87 0)
    (ConceptNode "R1")
    (ListLink (stv 1 0)
        (ConceptNode "X1")
    )
)
(SubsetLink (stv 0.99 0.99)
    (ConceptNode "Osama")
    (ConceptNode "AlQaeda")
)
(SubsetLink (stv 0.99 0.99)
    (ConceptNode "AlQaeda")
    (ConceptNode "Abu")
)
(SubsetLink (stv 0.99 0.99)
    (ConceptNode "Abu")
    (ConceptNode "AlQaeda")
)
(SubsetLink (stv 0.99 0.99)
    (ConceptNode "Muhammad")
    (ConceptNode "AlQaeda")
)
(InheritanceLink (stv 0.95 0.99)
    (ConceptNode "AlQaeda")
    (ConceptNode "Osama")
)
(InheritanceLink (stv 0.95 0.99)
    (ConceptNode "Abu")
    (ConceptNode "terrorist")
)
(InheritanceLink (stv 0.99 0.99)
    (ConceptNode "Moses")
    (ConceptNode "killer")
)
(InheritanceLink (stv 0.99 0.99)
    (ConceptNode "Judea")
    (ConceptNode "killer")
)
;
; Say goodnight!

